### ISSUE TITLE
Hydration failed because the server rendered HTML didn't match the client.

### ISSUE THREAD

**Issue by Dakuan** [TwicPics/components#115]
Since upgrading from nextjs14-> nextjs15 (and therefore from react 18 -> 19) all server side rendered `TwicImg` components are throwing hydration warning, seems to be related to the twic-done class

```
Error: A tree hydrated but some attributes of the server rendered HTML didn't match the client properties. This won't be patched up. This can happen if a SSR-ed Client Component used:

- A server/client branch `if (typeof window !== 'undefined')`.
- Variable input such as `Date.now()` or `Math.random()` which changes each time it's called.
- Date formatting in a user's locale which doesn't match the server.
- External changing data without sending a snapshot of it along with the HTML.
- Invalid HTML tag nesting.

It can also happen if the client has a browser extension installed which messes with the HTML before React loaded.

https://react.dev/link/hydration-mismatch

  ...
    <ScrollAndFocusHandler segmentPath={[...]}>
      <InnerScrollAndFocusHandler segmentPath={[...]} focusAndScrollRef={{apply:false, ...}}>
        <ErrorBoundary errorComponent={undefined} errorStyles={undefined} errorScripts={undefined}>
          <LoadingBoundary hasLoading={false} loading={undefined} loadingStyles={undefined} loadingScripts={undefined}>
            <NotFoundBoundary notFound={undefined} notFoundStyles={undefined}>
              <RedirectBoundary>
                <RedirectErrorBoundary router={{...}}>
                  <InnerLayoutRouter parallelRouterKey="children" url="/posts/Xqy..." tree={[...]} childNodes={Map} ...>
                    <PostDetailRoute>
                      <PostsDetailPage post={{id:"87c6db...", ...}}>
                        <dt className="hover:curs..." src="toggr/prod..." ratio="3000/2091">
                          <div ref={{current:null}} className={"twic-i h..."} style={{}}>
                            <rt className="" src="toggr/prod..." ratio="3000/2091" mediaTag="img">
                              <div suppressHydrationWarning={true} className="twic-w twi..." style={{...}} ...>
                                <img
                                  ref={{current:null}}
                                  alt=""
                                  style={{objectFit:"cover"}}
                                  data-twic-src="media:toggr/production/users/d895affa-326f-4d9e-96b8-cce10e336b0b/pos..."
-                                 className={" twic-done"}
-                                 src="https://toggr.twic.pics/toggr/production/users/d895affa-326f-4d9e-96b8-cce10e33..."
                                >
                                ...
                    ...

    at createUnhandledError (http://localhost:3000/_next/static/chunks/node_modules_next_dist_client_34bfc0._.js:744:19)
    at handleClientError (http://localhost:3000/_next/static/chunks/node_modules_next_dist_client_34bfc0._.js:846:56)
    at console.error (http://localhost:3000/_next/static/chunks/node_modules_next_dist_client_34bfc0._.js:977:56)
    at emitPendingHydrationWarnings (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:2759:103)
    at completeWork (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:7364:32)
    at runWithFiberInDEV (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:631:20)
    at completeUnitOfWork (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:7987:23)
    at performUnitOfWork (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:7929:28)
    at workLoopSync (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:7820:40)
    at renderRootSync (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:7801:13)
    at performWorkOnRoot (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:7544:148)
    at performSyncWorkOnRoot (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:8386:9)
    at flushSyncWorkAcrossRoots_impl (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:8313:199)
    at processRootScheduleInMicrotask (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:8330:9)
    at http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:8397:126````

**Comment by mbgspcii** [comment]
Hi @Dakuan .
Thank you for opening this issue.
We're looking into how to fix this situation and will get back to you as soon as possible.

**Comment by mbgspcii** [comment]
Hi again @Dakuan.
I have no issue on my side but we'll keep looking.... 
Can you check in `incognito` mode please (just to know if it related to a browser extension) ?

**Comment by Dakuan** [comment]
hello, same in incognito

![image](https://github.com/user-attachments/assets/382275fb-b78f-4da1-b04c-f37a33662758)

**Comment by mbgspcii** [comment]
Hi @Dakuan 
Here's an extract from my package.json file: 
```
  "dependencies": {
    "@twicpics/components": "0.31.0",
    "react": "19.0.0-rc-02c0e824-20241028",
    "react-dom": "19.0.0-rc-02c0e824-20241028",
    "next": "15.0.2"
  }

```
Do you have the same thing? If not, could you send us your dependencies?

If applicable, could you please share with us an extract from your implementation of a case that causes this warning?

**Comment by mbgspcii** [comment]
Hi @Dakuan 

We were unable to reproduce your anomaly.
Could you please see if the [0.31.1-beta.0](https://www.npmjs.com/package/@twicpics/components/v/0.31.1-beta.0) version fixes your problem?
Don't hesitate to keep us informed.
